### ISSUE TITLE
Circular @VertxGen types don't work

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-js#36]
reproducer: create 2 @VertxGen interfaces, each one depending on each other (for instance method return type)

issue: each type needs a require on each other, the underlying module system can only honour one and the other is undefined, see https://nodejs.org/api/modules.html

**Comment by pmlopes** [comment]
They can work but we might need to rewrite the whole js lang template and probably re-implement the loader.

In nodejs the loader has the concept of incomplete copy, however for this to work we probably need to write code in a "prototypable" way because at this moment we can load another module after a constructor function is defined and the come back and add the extra methods to the prototype.
